### When loading the below dataframe from csv, it creates a redundant index column called Unnamed: 0. 

Heres how to get rid of it:

In [25]:
data = pd.read_csv('data_for_prep.csv')
data[:20]

    Unnamed: 0  preg  plas  pres  skin  test  mass   pedi  age  class
0            0     6   148    72    35     0  33.6  0.627   50      1
1            1     1    85    66    29     0  26.6  0.351   31      0
2            2     8   183    64     0     0  23.3  0.672   32      1
3            3     1    89    66    23    94  28.1  0.167   21      0
4            4     0   137    40    35   168  43.1  2.288   33      1
5            5     5   116    74     0     0  25.6  0.201   30      0
6            6     3    78    50    32    88  31.0  0.248   26      1
7            7    10   115     0     0     0  35.3  0.134   29      0
8            8     2   197    70    45   543  30.5  0.158   53      1
9            9     8   125    96     0     0   0.0  0.232   54      1
10          10     4   110    92     0     0  37.6  0.191   30      0
11          11    10   168    74     0     0  38.0  0.537   34      1
12          12    10   139    80     0     0  27.1  1.441   57      0
13          13     1   189    60    23   846  30.1  0.398   59      1
14          14     5   166    72    19   175  25.8  0.587   51      1
15          15     7   100     0     0     0  30.0  0.484   32      1
16          16     0   118    84    47   230  45.8  0.551   31      1
17          17     7   107    74     0     0  29.6  0.254   31      1
18          18     1   103    30    38    83  43.3  0.183   33      0
19          19     1   115    70    30    96  34.6  0.529   32      1

<b>>>>SCROLL DOWN FOR ANSWER<<<

---

In [23]:
data = pd.read_csv('data_for_prep.csv',index_col=0)
data[:10]

   preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1
5     5   116    74     0     0  25.6  0.201   30      0
6     3    78    50    32    88  31.0  0.248   26      1
7    10   115     0     0     0  35.3  0.134   29      0
8     2   197    70    45   543  30.5  0.158   53      1
9     8   125    96     0     0   0.0  0.232   54      1

---

---

In [3]:
import pandas as pd